#!/usr/bin/env python3
import os
import sys
import logging
import importlib

run_root = os.path.join(os.getcwd(), "src")
sys.path.insert(1, run_root)

from src.config import RCConfig
from src.server import RCServer

if __name__=="__main__":
    if len(sys.argv) < 2:
        print("Arguments missing!")
        sys.exit()

    config_path = sys.argv[1]
    config = RCConfig(config_path)
    server = RCServer(config)

    server.start()
